window.VaingloryHeroData = {
    Adagio:{A:'Gift of Fire',B:'Agent Of Wrath',C:'Verse of Judgement',Perk:'Arcane Renewal'},
    Alpha:{A:'Prime Directive',B:'Core Charge',C:'Termination Protocol',Perk:'Infinite Reboot'},
    Ardan:{A:'Vanguard',B:'Blood for Blood',C:'Gauntlet',Perk:'Julia\'s Gift'},
    Baron:{A:'Porcupine Mortar',B:'Jump Jets',C:'Ion Cannon',Perk:'Rocket Launcher'},
    Baptiste:{A:'Bad Mojo',B:'Ordained',C:'Fearsome Shade',Perk:'Reap'},
    Blackfeather:{A:'Feint of Heart',B:'On Point',C:'Rose Offensive',Perk:'Heartthrob'},
    Catherine:{A:'Merciless Persuit',B:'Stormguard',C:'Blast Tremor',Perk:'Captain of the Guard'},
    Celeste:{A:'Heliogenesis',B:'Core Collapse',C:'Solar Storm',Perk:'Julia\'s Light'},
    Flicker:{A:'Binding Light',B:'Fairy Dust',C:'Moon Cloak',Perk:'Willow Whisper'},
    Fortress:{A:'Truth of the Tooth',B:'Law of the Claw',C:'Attack of the Pack',Perk:'Packmates'},
    Glaive:{A:'Afterburn',B:'Twisted Stroke',C:'Bloodsong',Perk:'Hunt the Weak'},
    Grace:{A:'Benediction',B:'Holy Nova',C:'Divine Intervention',Perk:'Retribution'},
    Grumpjaw:{A:'Grumpy',B:'Hangry',C:'Stuffed',Perk:'Living Armor'},
    Gwen:{A:'Buckshot Bonanza',B:'Skedaddle',C:'Aces High',Perk:'Boomstick'},
    Idris:{A:'Shroudstep',B:'Chakram',C:'Shimmer Strike',Perk:'Divergent Paths'},
    Joule:{A:'Rocket Leap',B:'Thunder Strike',C:'Big Red Button',Perk:'Heavy Plating'},
    Kestrel:{A:'Glimmershot',B:'Active Camo',C:'One Shot One Kill',Perk:'Adrenaline'},
    Koshka:{A:'Pouncy Fun',B:'Twirly Death',C:'Yummy Catnip Frenzy',Perk:'Bloodrush'},
    Krul:{A:'Dead Man\'s Rush',B:'Smite',C:'From Hell\'s Heart',Perk:'Shadows Empower Me'},
    Lance:{A:'Impale',B:'Gythian wall',C:'Combat Roll',Perk:'Partisan\'s Technique'},
    Lyra:{A:'Imperial Sigil',B:'Bright Bulwark',C:'Arcane Passage',Perk:'Principle Arcanum'},
    Ozo:{A:'Three-Ring Circus',B:'Acrobounce',C:'Bangarang',Perk:'Carnie Luck'},
    Petal:{A:'Bramblebloom Seeds',B:'Trampoline',C:'Spontaneous Combustion',Perk:'Munions'},
    Phinn:{A:'Quibble',B:'Polite Company',C:'Forced Accord',Perk:'Unstoppable'},
    Reim:{A:'Winter Spire',B:'Chill Winds',C:'Valkyrie',Perk:'Frostguard'},
    Reza:{A:'Scorcher',B:'Troublemaker',C:'Netherform Detonator',Perk:'Firestarter'},
    Ringo:{A:'Achilles Shot',B:'Twirling Silver',C:'Hellfire Brew',Perk:'Double Down'},
    Rona:{A:'Into the Fray',B:'Foesplitter',C:'Red Mist',Perk:'Berserkers\' Fury'},
    Samuel:{A:'Malice & Verdict',B:'Drifting Dark',C:'Oblivion',Perk:'Corrupted Genius'},
    SAW:{A:'Roadie Run',B:'Suppressing Fire',C:'Mad Cannon',Perk:'Spin Up'},
    Skaarf:{A:'Spitfire',B:'Goop',C:'Dragon Breath',Perk:'Fan the Flames'},
    Skye:{A:'Forward Barrage',B:'Suri Strike',C:'Death From Above',Perk:'Target Lock'},
    Taka:{A:'Kaiten',B:'Kaku',C:'X-Retsu',Perk:'House Kamuha'},
    Vox:{A:'Sonic Zoom',B:'Pulse',C:'Wait For It ...',Perk:'Julia\'s Song'}
};
